# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    projects: '**/*.csproj'
    arguments: '--output publish_output --configuration Release'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: 'publish_output/'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
    replaceExistingArchive: true 
    archiveType: 'zip' 

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  
- task: AzureFunctionApp@1
  displayName: 'Azure Function App Deploy: jebrook-linuxconsumptionpython'
  inputs:
    azureSubscription: 'Jebrook Sub (7317be97-c6d6-4ef8-9173-809f4614654e)'
    appType: functionApp
    appName: 'jebrook-linuxconsumptionpython'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: zipDeploy

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
